### ISSUE TITLE
issue on window because file is not Dirent object

### ISSUE THREAD

**Issue by qtbrtchip** [Yqnn/node-readdir-glob#1]
@Yqnn 
https://github.com/Yqnn/node-readdir-glob/blob/2a97b77ccb030cedc2b8d55c82f0a3e12beb9312/index.js#L65

Can we change the line with this
`const filename = dir + '/' + (typeof file === 'string' ? file : file.name);`

**Comment by Yqnn** [comment]
Are you using a NodeJS older than 10.10.0 ?

[Official doc](https://nodejs.org/api/fs.html#fs_fs_readdir_path_options_callback) says:
> If `options.withFileTypes` is set to `true`, the `files` array will contain [fs.Dirent](https://nodejs.org/api/fs.html#fs_class_fs_dirent) objects.

But it seems `withFileTypes` is only supported from node v10.10.0.
I can make a patch to ensure the lib also works with node 10.0.

**Comment by qtbrtchip** [comment]
Yup, I am wrong. I am using version Nodejs 10.4. It is not supported.

**Comment by qtbrtchip** [comment]
@Yqnn If you can patch to support node 10.0, it would be great.
