### ISSUE TITLE
Dependency minimatch contains CWE-1333 vulnerability

### ISSUE THREAD

**Issue by Fotiman** [Yqnn/node-readdir-glob#15]
The minimatch package is vulnerable to Regular Expression Denial of Service (ReDoS) attacks.
Weakness: https://cwe.mitre.org/data/definitions/1333.html
Advisory: https://www.huntr.dev/bounties/e4e1393c-d590-4492-9f43-8be3f3321629/

The current version of readdir-glob specifies the dependency on minimatch as version "^3.0.4".  The vulnerability is removed in minimatch patch version 3.0.6, so to eliminate the nested vulnerability from readdir-glob, the dependency should be updated to "^3.0.6" (or newer).

**Comment by Yqnn** [comment]
Thanks for the report 👍 
It's fixed in version 1.1.2 .
