### ISSUE TITLE
 Unexpected token * on index.js:62

### ISSUE THREAD

**Issue by Gajendra108** [Yqnn/node-readdir-glob#3]
I am getting below error for https://github.com/Yqnn/node-readdir-glob/blob/ebf4ba6be3e1f3ca8247efa7c1691aef2913e9a1/index.js#L62  :

Error : 
/app/node_modules/readdir-glob/index.js:62
--
  | async function* exploreWalkAsync(dir, path, followSyslinks, useStat, shouldSkip, strict) {
  | ^
  |  
  | SyntaxError: Unexpected token *
  | at createScript (vm.js:80:10)
  | at Object.runInThisContext (vm.js:139:10)
  | at Module._compile (module.js:607:28)
  | at Object.Module._extensions..js (module.js:654:10)
  | at Module.load (/app/node_modules/coffeescript/lib/coffee-script/register.js:45:36)

**Comment by Yqnn** [comment]
Please ensure you use at least NodeJS 10.
